services:
  pdfmind:
    build:
      context: .
      dockerfile: Dockerfile
    image: pdfmind
    container_name: pdfmind
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./doc.pdf:/app/doc.pdf:ro
    stdin_open: true
    tty: true
    restart: "no"
